"""OSAP adapter — external candidate library from Open Source Asset Pricing.

Chen & Zimmermann (2022), "Open Source Cross-Sectional Asset Pricing",
Critical Finance Review 11(2), 207-264.  https://www.openassetpricing.com/

WHY THIS EXISTS (the circularity anchor)
----------------------------------------
Every candidate in the 179-candidate bank was designed by this project's own
agents, and every null it was judged against was generated by the same agents.
NEGATIVE_RESULTS 34's meta-lesson ("the instrument that adjudicates everything
else must itself be adjudicated") therefore still has one unmeasured leg: the
CANDIDATE POPULATION is ours too.

OSAP fixes that leg. It ships 331 documented signals built by an independent
team from the published literature, keyed by (permno, yyyymm) — the exact join
key of `data/crsp_panel_2002`:

    Predictor  212   signals the source paper found predictive
    Placebo    114   signals the literature considered and found NON-predictive
    Drop         5   withdrawn

The 114 PLACEBOS are the asset. They are an externally curated null set of
real, economically-motivated, publishable constructions that happen not to
predict — i.e. exactly the population a factory generates, built by people with
no stake in this project's gates. Running the frozen ladder over them yields an
FDR estimate with NO simulator and NO Aegis-authored randomness in it.

DIRECTION IS NOT OURS TO CHOOSE
-------------------------------
`Sign` comes from the OSAP documentation, i.e. from the original paper. It is
read from the doc table BEFORE any scan runs and is never flipped. This keeps
CANON 6 intact: a sign flip is a new candidate in a future cohort, never a
retry (cf. NEGATIVE_RESULTS 27, where a frozen +1 on os_ratio printed t_ic
-6.11 and was recorded as a miss rather than re-cut).

TIMING CONVENTION (frozen, stated because it is the one real assumption)
------------------------------------------------------------------------
OSAP publishes each signal at the month in which it is usable to predict the
FOLLOWING month's return. `explore.scan_signal` reads the score at formation
month m-1 and the realized return at test month m. So OSAP yyyymm maps to the
formation month with NO additional lag. `EXTRA_LAG_MONTHS` makes that explicit
and auditable; set it to 1 for a paranoid arm and report both.

KNOWN LIMITATION, DISCLOSED
---------------------------
Not every documented acronym is downloadable at firm level; `dl_signal` warns
"One or more input predictors are not available" and silently returns only the
available columns. `load_osap_signals` therefore RAISES on any requested
acronym that does not come back, rather than quietly scanning a smaller set —
the silent-shrink failure mode is NEGATIVE_RESULTS 5 wearing a new hat.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass

import pandas as pd

from aegis_brain.data.eodhd_panel import Panel
from aegis_brain.factory.signals import FactorySignal

logger = logging.getLogger(__name__)

EXTRA_LAG_MONTHS = 0        # frozen; see TIMING CONVENTION above
CAT_PREDICTOR = "Predictor"
CAT_PLACEBO = "Placebo"


@dataclass(frozen=True)
class OSAPMeta:
    """Provenance carried next to every scan row, so a result is never quoted
    without the paper it came from."""

    acronym: str
    authors: str
    year: int
    journal: str
    category: str               # Predictor | Placebo | Drop
    sign: int                   # +1 / -1, from the ORIGINAL paper
    sample_start: int
    sample_end: int
    rep_quality: str


def load_doc() -> pd.DataFrame:
    """The OSAP signal documentation table (331 rows)."""
    import openassetpricing as oap

    return oap.OpenAP().dl_signal_doc("pandas")


def _sign_of(row: pd.Series) -> int:
    s = row.get("Sign")
    try:
        v = int(float(s))
    except (TypeError, ValueError):
        return 1
    return -1 if v < 0 else 1


def meta_table(doc: pd.DataFrame, category: str | None = None) -> list[OSAPMeta]:
    d = doc if category is None else doc[doc["Cat.Signal"] == category]
    out = []
    for _, r in d.iterrows():
        out.append(OSAPMeta(
            acronym=str(r["Acronym"]),
            authors=str(r.get("Authors", "")),
            year=int(r["Year"]) if pd.notna(r.get("Year")) else 0,
            journal=str(r.get("Journal", "")),
            category=str(r["Cat.Signal"]),
            sign=_sign_of(r),
            sample_start=int(r["SampleStartYear"]) if pd.notna(
                r.get("SampleStartYear")) else 0,
            sample_end=int(r["SampleEndYear"]) if pd.notna(
                r.get("SampleEndYear")) else 0,
            rep_quality=str(r.get("Signal Rep Quality", "")),
        ))
    return out


def download_long(acronyms: list[str]) -> pd.DataFrame:
    """Long frame [permno, yyyymm, <acronym>...] for the requested signals.

    Raises if any requested acronym is missing from the response — see the
    silent-shrink note in the module docstring.
    """
    import openassetpricing as oap

    df = oap.OpenAP().dl_signal("pandas", acronyms)
    got = [c for c in df.columns if c not in ("permno", "yyyymm")]
    missing = sorted(set(acronyms) - set(got))
    if missing:
        raise ValueError(
            f"OSAP returned {len(got)}/{len(acronyms)} signals; missing: "
            f"{missing[:10]}{'...' if len(missing) > 10 else ''}. "
            "Refusing to scan a silently reduced set.")
    return df


class ScoreGridder:
    """Fast (month x permno) reshape shared across every signal in a chunk.

    `pivot_table` re-derives the row/column mapping for every signal, which
    costs ~2.5 minutes per signal on a 5.4M-row frame. The mapping is identical
    for all signals in a chunk, so it is computed ONCE here and each signal
    becomes a single vectorised scatter into a preallocated array.

    Rows whose (month, permno) fall outside the panel are dropped, exactly as a
    reindex would drop them. Duplicate (month, permno) keys keep the LAST
    occurrence, matching `pivot_table(aggfunc="last")`.
    """

    def __init__(self, long_df: pd.DataFrame, panel: Panel) -> None:
        import numpy as np

        months = panel.monthly_ret.index
        syms = panel.monthly_ret.columns
        self.shape = (len(months), len(syms))
        self.index, self.columns = months, syms

        m = pd.to_datetime(long_df["yyyymm"].astype("int64").astype(str),
                           format="%Y%m") + pd.offsets.MonthEnd(0)
        row = months.get_indexer(m)
        col = syms.get_indexer(
            pd.Index(long_df["permno"].astype("int64").astype(str)))
        keep = (row >= 0) & (col >= 0)
        self.row = row[keep]
        self.col = col[keep]
        self.keep = keep
        self._np = np

    def grid(self, values: pd.Series) -> pd.DataFrame:
        np = self._np
        out = np.full(self.shape, np.nan, dtype="float64")
        v = values.to_numpy(dtype="float64", na_value=np.nan)[self.keep]
        out[self.row, self.col] = v          # last write wins, as aggfunc="last"
        return pd.DataFrame(out, index=self.index, columns=self.columns)


def to_score_frame(long_df: pd.DataFrame, acronym: str, panel: Panel,
                   extra_lag: int = EXTRA_LAG_MONTHS) -> pd.DataFrame:
    """Pivot one OSAP signal onto the panel's [month-end x permno-string] grid.

    Reindexes onto the panel exactly: no forward-fill, no interpolation. A
    month-permno cell the signal does not cover stays NaN, and `scan_signal`
    drops it — which is the honest behaviour, because an OSAP signal legitimately
    does not exist for every firm-month.
    """
    if acronym not in long_df.columns:
        raise KeyError(f"{acronym!r} not in downloaded frame")

    d = long_df[["permno", "yyyymm", acronym]].dropna(subset=[acronym])
    # yyyymm (e.g. 200401) -> that calendar month's END, matching the panel index
    dt = pd.to_datetime(d["yyyymm"].astype(int).astype(str), format="%Y%m")
    d = d.assign(month=dt + pd.offsets.MonthEnd(0),
                 sym=d["permno"].astype(int).astype(str))

    wide = d.pivot_table(index="month", columns="sym", values=acronym,
                         aggfunc="last")
    if extra_lag:
        wide = wide.shift(extra_lag)
    return wide.reindex(index=panel.monthly_ret.index,
                        columns=panel.monthly_ret.columns)


def build_signals(long_df: pd.DataFrame, metas: list[OSAPMeta],
                  panel: Panel) -> list[FactorySignal]:
    """FactorySignal objects the existing explore/confirm harness can scan.

    Scores are materialised ONCE here and closed over, so `compute` is a pure
    lookup — a 200-signal batch does not re-pivot 2.7M rows per scan.
    """
    out: list[FactorySignal] = []
    gridder = ScoreGridder(long_df, panel)
    for m in metas:
        if m.acronym not in long_df.columns:
            continue
        frame = gridder.grid(long_df[m.acronym])
        if EXTRA_LAG_MONTHS:
            frame = frame.shift(EXTRA_LAG_MONTHS)
        cover = float(frame.notna().sum(axis=1).mean())
        if cover < 100:
            logger.warning("osap %s: mean coverage %.0f names/month — below the "
                           "scan's 100-name floor, it will produce no months",
                           m.acronym, cover)
        # SIGN CORRECTION (2026-08-08, INSTR-ERA-BACKTEST-1 P4 catch): the
        # wide download is `signed_predictors_dl_wide` — columns arrive
        # PRE-SIGNED by OSAP (higher value = higher predicted return).
        # Applying the doc Sign again double-flips every -1 signal; proven
        # empirically by osap_MaxRet small t_ic -7.74 vs the internal
        # same-construction +7.71. direction is therefore ALWAYS +1; the
        # doc Sign stays in the hypothesis as provenance only.
        out.append(FactorySignal(
            name=f"osap_{m.acronym}",
            hypothesis=(f"{m.authors} ({m.year}), {m.journal}. OSAP "
                        f"{m.category}, sample {m.sample_start}-{m.sample_end}, "
                        f"rep quality {m.rep_quality}. Column pre-signed by "
                        f"OSAP (doc Sign {m.sign:+d}, already applied at "
                        f"source)."),
            compute=(lambda _p, _f=frame: _f),
            direction=+1,
            contaminated=False,
        ))
    return out
