"""GRAPH-COVARIANCE-1 — render the report tables from the run artifacts.

    python -m scripts.gc1_tables > runs/GRAPH-COVARIANCE-1/tables.md

Every number in the verdict document comes from here. Nothing is retyped: a
number that a human copied is a number that can drift from its receipt, and this
project has already paid for that lesson once.
"""

from __future__ import annotations

import glob
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from aegis_brain.config import MODULE_ROOT              # noqa: E402
from scripts import gc1_config as G                     # noqa: E402
from scripts.gc1_grade import paired                    # noqa: E402

OUT = MODULE_ROOT / "runs" / "GRAPH-COVARIANCE-1"

#: Display order, grouped by role. Role is fixed by the pre-registration, not
#: by how each arm scored.
ORDER = [
    ("decision", ["model_numeric", "model_semantic"]),
    ("placebo (must be null)", ["placebo_shuffled", "random_matched_density",
                                "placebo_stratified"]),
    ("instrument / oracle (never adoptable)", ["oracle_on_edges",
                                               "oracle_feature",
                                               "oracle_full"]),
    ("context (never deciding)", ["diagonal", "sample", "ledoit_wolf",
                                  "rmt_denoised"]),
]


def load_arms() -> dict:
    arms = {}
    for p in glob.glob(str(OUT / "arms" / "*.json")):
        if "__floor" in Path(p).name:
            continue
        r = json.loads(Path(p).read_text(encoding="utf-8"))
        arms[r["arm"]] = r
    return arms


def verdict_word(s: dict) -> str:
    if s["detectable_improvement"]:
        return "**LOWER RISK**"
    if -s["risk_reduction"] >= s["mde"]:
        return "**detectably WORSE**"
    return "not detectable"


def main() -> int:
    arms = load_arms()
    ref = arms["model_numeric"]

    print("<!-- generated by scripts/gc1_tables.py — do not edit by hand -->\n")
    print(f"Eigenvalue floor {G.EIG_FLOOR_REL} (relative to the mean eigenvalue "
          f"of a correlation matrix, which is 1). Entry clip {G.CORR_CLIP}. "
          f"Purge {G.PURGE}. MDE = {G.MDE_Z} x max(HAC, IID) SE over graded cut "
          f"dates, Newey-West at {G.NW_LAGS} lags.\n")

    # ── table 1: the arms themselves ────────────────────────────────────────
    print("## Table 1 — every arm, and whether its matrices are usable\n")
    print("| role | arm | realised resid-GMV vol | calibration "
          "(realised/predicted) | gross | effective bets | condition | VOID |")
    print("|---|---|---:|---:|---:|---:|---:|---|")
    for role, names in ORDER:
        for n in names:
            if n not in arms:
                continue
            a = arms[n]
            print(f"| {role} | `{n}` | {a['mean_vol_realised']:.5f} | "
                  f"{a['calibration_ratio']:.2f} | {a['mean_gross']:.2f} | "
                  f"{a['mean_eff_bets']:.0f} | {a['mean_cond']:.0f} | "
                  f"{'**VOID**' if a['VOID_numerically_degenerate'] else 'no'} |")

    # ── table 2: the paired comparisons ─────────────────────────────────────
    for key, label, unit in (
            ("vol_realised", "PRIMARY — residual minimum-variance portfolio",
             "annualised vol"),
            ("lo_vol_realised",
             "SECONDARY (H2) — long-only capped total-return portfolio",
             "annualised vol")):
        print(f"\n## Table 2{'a' if key == 'vol_realised' else 'b'} — "
              f"{label}\n")
        print(f"Paired within each cut date, then one SE over the date-level "
              f"differences. Positive = the arm realised LOWER risk than "
              f"`model_numeric`. Units: {unit}.\n")
        print("| arm | risk reduction | as % of ref | MDE | t | n dates | "
              "reading |")
        print("|---|---:|---:|---:|---:|---:|---|")
        for role, names in ORDER:
            for n in names:
                if n == "model_numeric" or n not in arms:
                    continue
                s = paired(ref, arms[n], key)
                print(f"| `{n}` | {s['risk_reduction']:+.6f} | "
                      f"{s['risk_reduction_pct_of_ref']:+.2f}% | "
                      f"{s['mde']:.6f} | {-s['t']:+.2f} | "
                      f"{s['n_common_dates']} | {verdict_word(s)} |")
        print(f"\n`model_numeric` reference level: "
              f"{ref['mean_vol_realised' if key == 'vol_realised' else 'lo_mean_vol_realised']:.5f}")

    # ── table 2c: the headroom bound ────────────────────────────────────────
    if "sample" in arms and "oracle_full" in arms and "diagonal" in arms:
        head = paired(arms["sample"], arms["oracle_full"], "vol_realised")
        span = paired(arms["diagonal"], arms["sample"], "vol_realised")
        frac = (head["mde"] / span["risk_reduction"] * 100.0
                if span["risk_reduction"] else float("nan"))
        print("\n## Table 2c — how much headroom is left above the trailing "
              "sample matrix\n")
        print("`not detectable` is not `zero` (§19), so the null is reported as "
              "a BOUND.\n")
        print("| quantity | value |")
        print("|---|---:|")
        print(f"| risk reduction of `oracle_full` over `sample` (perfect "
              f"foresight vs the trailing matrix; negative = perfect foresight "
              f"realised HIGHER risk) | {head['risk_reduction']:+.6f} |")
        print(f"| its MDE | {head['mde']:.6f} |")
        print(f"| its t | {-head['t']:+.2f} |")
        print(f"| reading | {verdict_word(head)} |")
        print(f"| `sample − diagonal` (the whole gain from knowing the trailing "
              f"matrix at all) | {span['risk_reduction']:+.6f} |")
        print(f"| **remaining headroom, as a share of that gain** | "
              f"**≤ {frac:.1f}%** |")
        print(f"\nAny correlation predictor — semantic, numerical or omniscient "
              f"— is competing for at most {frac:.1f}% of the gain the trailing "
              f"sample matrix already delivers over the diagonal assumption. "
              f"The semantic graph covers 0.58% of pairs.")

    # ── table 3: the gate ───────────────────────────────────────────────────
    gp = OUT / "gate_report.json"
    if gp.exists():
        g = json.loads(gp.read_text(encoding="utf-8"))
        print("\n## Table 3 — the pre-registered power gate\n")
        print("| quantity | value |")
        print("|---|---|")
        print(f"| gate passed as written | "
              f"**{'YES' if g['passed'] else 'NO'}** |")
        print(f"| metric responds to a better matrix (`oracle_full`) | "
              f"**{'YES' if g['metric_responds_to_a_better_matrix'] else 'NO'}** |")
        print(f"| architecture ceiling detectable (`oracle_feature`) | "
              f"**{'YES' if g.get('architecture_ceiling_detectable') else 'NO'}** |")
        print(f"| voided arms | {g['voided_arms'] or 'none'} |")
        print(f"\n> {g['verdict']}")

    # ── table 4: the floor sensitivity ──────────────────────────────────────
    fp = OUT / "floor_sensitivity.json"
    if fp.exists():
        s = json.loads(fp.read_text(encoding="utf-8"))
        print("\n## Table 4 — eigenvalue-floor sensitivity (can only DEMOTE)\n")
        print("| floor | H1: semantic − numeric | MDE | t | reading | "
              "headroom: oracle_full − sample | its MDE | reading |")
        print("|---|---:|---:|---:|---|---:|---:|---|")
        for k in sorted([x for x in s if x.replace('.', '', 1).isdigit()],
                        key=float):
            v = s[k]["primary_residual_gmv"]
            h = s[k].get("headroom_oracle_full_minus_sample")
            hcell = (f"{h['risk_reduction']:+.6f} | {h['mde']:.6f} | "
                     f"{verdict_word(h)}" if h else "— | — | —")
            print(f"| {k} | {v['risk_reduction']:+.6f} | {v['mde']:.6f} | "
                  f"{-v['t']:+.2f} | {verdict_word(v)} | {hcell} |")
        print(f"\nstable sign: **{s['stable_sign']}** · stable reading: "
              f"**{s.get('stable_label', s.get('stable_detectability'))}** · "
              f"headroom absent at every floor: "
              f"**{s.get('headroom_absent_at_every_floor')}**"
              f"\n\n> {s['reading']}")

    # ── table 5: the voided first run, disclosed ────────────────────────────
    vp = OUT / "void_run_eigfloor_1e-8" / "gate_report.json"
    if vp.exists():
        v = json.loads(vp.read_text(encoding="utf-8"))
        print("\n## Table 5 — the VOIDED first run, disclosed with its numbers\n")
        va = {}
        for n in ("model_numeric", "oracle_on_edges"):
            f = OUT / "void_run_eigfloor_1e-8" / f"{n}.json"
            if f.exists():
                va[n] = json.loads(f.read_text(encoding="utf-8"))
        print("| arm | realised vol | predicted vol | calibration | condition | "
              "gross |")
        print("|---|---:|---:|---:|---:|---:|")
        for n, a in va.items():
            print(f"| `{n}` | {a['mean_vol_realised']:.5f} | "
                  f"{a['mean_vol_predicted']:.5f} | "
                  f"{a['calibration_ratio']:.0f} | {a['mean_cond']:.3g} | "
                  f"{a['mean_gross']:.2f} |")
        print(f"\nRun at an ABSOLUTE eigenvalue floor of 1e-8. A matrix that "
              f"forecasts {va['model_numeric']['mean_vol_predicted']:.5f} "
              f"annualised volatility for a portfolio realising "
              f"{va['model_numeric']['mean_vol_realised']:.5f} is not a risk "
              f"model. Void on that number alone, independent of any arm "
              f"comparison.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
